apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: dungleonhart/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000