apiVersion: v1
kind: Service
metadata:
  name: main-app-service
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: LoadBalancer